export const types = {
    // Sync
    FILL_TASKS:               'FILL_TASKS',
    CREATE_TASK:              'CREATE_TASK',
    REMOVE_TASK:              'REMOVE_TASK',
    UPDATE_TASK:              'UPDATE_TASK',
    COMPLETE_ALL_TASK:        'COMPLETE_ALL_TASK',
    UPDATE_NEW_TASK_MESSAGE:  'UPDATE_NEW_TASK_MESSAGE',
    UPDATE_EDIT_TASK_MESSAGE: 'UPDATE_EDIT_TASK_MESSAGE',
    UPDATE_TASKS_FILTER:      'UPDATE_TASKS_FILTER',
    SET_EDIT_TASK_ID:         'SET_EDIT_TASK_ID',
    RESET_EDIT_TASK_ID:       'RESET_EDIT_TASK_ID',

    // Async
    FETCH_TASKS_ASYNC:       'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC:       'CREATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC:       'REMOVE_TASK_ASYNC',
    UPDATE_TASK_ASYNC:       'UPDATE_TASK_ASYNC',
    COMPLETE_ALL_TASK_ASYNC: 'COMPLETE_ALL_TASK_ASYNC',
};
